version: "2"

volumes:
  db-volume:

services:
  db:
    image: postgres
    ports:
    - "5432:5432"
    volumes:
    - ./db/data:/var/lib/postgresql/data
  db-dev:
    image: postgres
    ports:
    - "5432:5432"
    volumes:
    - db-volume:/var/lib/postgresql/data
  nats:
    image: nats
    ports:
    - "4222:4222"
    - "8222:8222"


  influxdb:
    image: influxdb:1.7
    ports:
    - "8086:8086"
    volumes:
    - ./influxdb:/var/lib/influxdb
  chronograf:
    image: chronograf:1.7
    ports:
    - "8888:8888"
    volumes:
    - ./chronograf:/var/lib/chronograf
    environment:
    - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
    - GOOGLE_DOMAINS=$GOOGLE_DOMAINS
    - PUBLIC_URL=$PUBLIC_URL
    - TOKEN_SECRET=$TOKEN_SECRET
    - INFLUXDB_URL=http://influxdb:8086
    depends_on:
    - influxdb


  reverse-proxy:
    image: nginx
    ports:
    - "80:80"
    - "9090:9090"
    volumes:
    - ./reverse-proxy/conf.d/sotah.conf:/etc/nginx/conf.d/sotah.conf:ro
    - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - chronograf


  sotah-server-base:
    image: ihsw/sotah-server
    volumes:
    - ./sotah-server:/tmp/sotah-server
    environment:
    - CLIENT_ID=$CLIENT_ID
    - CLIENT_SECRET=$CLIENT_SECRET
    - NATS_HOST=nats
  sotah-server-api:
    extends: sotah-server-base
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug api
  sotah-server-live-auctions:
    extends: sotah-server-base
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug live-auctions
  sotah-server-pricelist-histories:
    extends: sotah-server-base
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug pricelist-histories

  sotah-server-base-production:
    extends: sotah-server-base
    image: gcr.io/$PROJECT_ID/server
    environment:
    - PROJECT_ID=$PROJECT_ID
    - INFLUX_HOST=$INFLUX_HOST
  sotah-server-base-fn:
    extends: sotah-server-base-production
    environment:
    - NATS_HOST=$NATS_HOST
    - NATS_PORT=$NATS_PORT
  sotah-server-prod-api:
    extends: sotah-server-base-production
    depends_on:
    - nats
    - influxdb
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug prod-api
  sotah-server-prod-metrics:
    extends: sotah-server-base-production
    depends_on:
    - nats
    - influxdb
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug prod-metrics
  sotah-server-prod-live-auctions:
    extends: sotah-server-base-production
    depends_on:
    - nats
    - influxdb
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug prod-live-auctions
  sotah-server-prod-pricelist-histories:
    extends: sotah-server-base-production
    depends_on:
    - nats
    - influxdb
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug prod-pricelist-histories
  sotah-server-prod-items:
    extends: sotah-server-base-production
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug prod-items
  sotah-server-prod-gateway:
    extends: sotah-server-base-production
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug prod-gateway
  
  sotah-server-transfer:
    extends: sotah-server-base-production
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug transfer

  sotah-server-fn-cleanup-pricelist-histories:
    extends: sotah-server-base-fn
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug fn-cleanup-pricelist-histories

  sotah-api-base:
    image: ihsw/sotah-api
    ports:
    - "8080:8080"
    environment:
    - NATS_HOST=nats
    - NATS_PORT=4222
    - DB_HOST=db
  sotah-api:
    extends: sotah-api-base
    depends_on:
    - nats
    - db
    volumes:
    - ./sotah-server/data/item-icons:/tmp/item-icons
  sotah-api-test:
    extends: sotah-api-base
    depends_on:
    - nats
    - db
  sotah-api-production:
    extends: sotah-api-base
    image: gcr.io/$PROJECT_ID/api
    depends_on:
    - nats
    environment:
    - IS_GCE_ENV=1
