version: "2"

volumes:
  db-volume:

services:
  db:
    image: postgres
    ports:
    - "5432:5432"
    volumes:
    - ./db/data:/var/lib/postgresql/data
  db-dev:
    image: postgres
    ports:
    - "5432:5432"
    volumes:
    - db-volume:/var/lib/postgresql/data
  nats:
    image: nats
    ports:
    - "4222:4222"
    - "8222:8222"


  influxdb:
    image: influxdb:1.6
    ports:
    - "8086:8086"
    volumes:
    - ./influxdb:/var/lib/influxdb
  chronograf:
    image: chronograf:1.6
    ports:
    - "8888:8888"
    volumes:
    - ./chronograf:/var/lib/chronograf
    command: --influxdb-url=http://influxdb:8086
    environment:
    - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
    - GOOGLE_DOMAINS=$GOOGLE_DOMAINS
    - PUBLIC_URL=$PUBLIC_URL
    - TOKEN_SECRET=$TOKEN_SECRET


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
    - discovery.type=single-node
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - TAKE_FILE_OWNERSHIP=1
    volumes:
    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    - ./elasticsearch/data:/usr/share/elasticsearch/data
  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.0
    ports:
    - "8911:8911"
    volumes:
    - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
    - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    ports:
    - "5601:5601"
    environment:
    - SERVER_NAME=localhost
    - XPACK_MONITORING_COLLECTION_ENABLED=true
    - ELASTICSEARCH_URL=http://$ELASTICSEARCH_HOST:9200
  oauth2-proxy:
    build: ./oauth2-proxy
    depends_on:
    - kibana
    ports:
    - "4180:4180"
    environment:
    - OAUTH2_PROXY_CLIENT_ID=$KIBANA_GOOGLE_CLIENT_ID
    - OAUTH2_PROXY_CLIENT_SECRET=$KIBANA_GOOGLE_CLIENT_SECRET
    - OAUTH2_PROXY_COOKIE_SECRET=$KIBANA_COOKIE_SECRET
    - GOOGLE_DOMAINS=$GOOGLE_DOMAINS
    - KIBANA_HOST=kibana


  reverse-proxy:
    image: nginx
    ports:
    - "80:80"
    - "9090:9090"
    environment:
    - NGINX_HOST=sotah.info
    - NGINX_PORT=80
    volumes:
    - ./reverse-proxy/conf.d/sotah.conf:/etc/nginx/conf.d/sotah.conf:ro
    - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - sotah-client-production
    - sotah-api-production
    - chronograf
    - oauth2-proxy


  sotah-server-base:
    image: ihsw/sotah-server
    volumes:
    - ./sotah-server:/tmp/sotah-server
    environment:
    - API_KEY=$API_KEY
    - NATS_HOST=nats
  sotah-server-base-production:
    extends: sotah-server-base
    image: gcr.io/$PROJECT_ID/server
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcloud-app-credentials.json
    - PROJECT_ID=$PROJECT_ID
    - LOGSTASH_HOST=$LOGSTASH_HOST
    - LOGSTASH_PORT=$LOGSTASH_PORT

  sotah-server-api:
    extends: sotah-server-base
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug api
  sotah-server-api-test:
    extends: sotah-server-base
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug api-test -d /tmp/sotah-server/test-fixtures
  sotah-server-api-production:
    extends: sotah-server-base-production
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug api
    volumes:
    - $GOOGLE_APPLICATION_CREDENTIALS:/tmp/gcloud-app-credentials.json
  
  sotah-server-live-auctions:
    extends: sotah-server-base
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug live-auctions
  sotah-server-live-auctions-production:
    extends: sotah-server-base-production
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug live-auctions
    volumes:
    - $GOOGLE_APPLICATION_CREDENTIALS:/tmp/gcloud-app-credentials.json
  
  sotah-server-pricelist-histories:
    extends: sotah-server-base
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug pricelist-histories
  sotah-server-pricelist-histories-production:
    extends: sotah-server-base-production
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug pricelist-histories
    volumes:
    - $GOOGLE_APPLICATION_CREDENTIALS:/tmp/gcloud-app-credentials.json

  sotah-server-sync-items-production:
    extends: sotah-server-base-production
    volumes:
    - $GOOGLE_APPLICATION_CREDENTIALS:/tmp/gcloud-app-credentials.json
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug sync-items

  sotah-server-prune-store-production:
    extends: sotah-server-base-production
    volumes:
    - $GOOGLE_APPLICATION_CREDENTIALS:/tmp/gcloud-app-credentials.json
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug prune-store

  sotah-server-reform-history-production:
    extends: sotah-server-base-production
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug reform-history


  sotah-api-base:
    image: ihsw/sotah-api
    ports:
    - "8080:8080"
    environment:
    - NATS_HOST=nats
    - NATS_PORT=4222
    - DB_HOST=db
  sotah-api:
    extends: sotah-api-base
    depends_on:
    - nats
    - db
    volumes:
    - ./sotah-server/data/item-icons:/tmp/item-icons
  sotah-api-test:
    extends: sotah-api-base
    depends_on:
    - nats
    - db
  sotah-api-production:
    extends: sotah-api-base
    image: gcr.io/$PROJECT_ID/api
    depends_on:
    - nats
    - db


  sotah-client-production:
    image: gcr.io/$PROJECT_ID/client
    ports:
    - "5000:5000"
