version: "2"

services:
  db:
    image: postgres
  nats:
    image: nats
    ports:
    - "4222:4222"


  influxdb:
    image: influxdb:1.6
    ports:
    - "8086:8086"
    volumes:
    - ./influxdb:/var/lib/influxdb
  telegraf:
    image: telegraf:1.7
    depends_on:
    - influxdb
    - nats
    - db
    - reverse-proxy
    volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /:/hostfs:ro
    privileged: true
    environment:
    - HOST_PROC=/hostfs/proc
  chronograf:
    image: chronograf:1.6
    depends_on:
    - influxdb
    ports:
    - "8888:8888"
    volumes:
    - ./chronograf:/var/lib/chronograf
    command: --influxdb-url=http://influxdb:8086
    environment:
    - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
    - GOOGLE_DOMAINS=$GOOGLE_DOMAINS
    - PUBLIC_URL=$PUBLIC_URL
    - TOKEN_SECRET=$TOKEN_SECRET


  reverse-proxy:
    image: nginx
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=sotah.info
    - NGINX_PORT=80
    volumes:
    - ./reverse-proxy/conf.d/sotah.conf:/etc/nginx/conf.d/sotah.conf:ro
    - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - sotah-client-production
    - sotah-api-production
    - chronograf


  sotah-server-base:
    image: ihsw/sotah-server
    volumes:
    - ./sotah-server:/tmp/sotah-server
    environment:
    - API_KEY=$API_KEY
    - NATS_HOST=nats
  
  sotah-server-live-auctions:
    extends: sotah-server-base
    depends_on:
    - nats
    - sotah-server-api
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug live-auctions
  sotah-server-live-auctions-production:
    extends: sotah-server-base
    depends_on:
    - nats
    - sotah-server-api-production
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug live-auctions
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcloud-app-credentials.json
    - PROJECT_ID=$PROJECT_ID
    volumes:
    - $GOOGLE_APPLICATION_CREDENTIALS:/tmp/gcloud-app-credentials.json
  
  sotah-server-pricelist-histories:
    extends: sotah-server-base
    depends_on:
    - nats
    - sotah-server-live-auctions
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug pricelist-histories
  sotah-server-pricelist-histories-production:
    extends: sotah-server-base
    depends_on:
    - nats
    - sotah-server-live-auctions-production
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug pricelist-histories
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcloud-app-credentials.json
    - PROJECT_ID=$PROJECT_ID
    volumes:
    - $GOOGLE_APPLICATION_CREDENTIALS:/tmp/gcloud-app-credentials.json

  sotah-server-api:
    extends: sotah-server-base
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug api
  sotah-server-api-test:
    extends: sotah-server-base
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug api-test -d /tmp/sotah-server/test-fixtures
  sotah-server-api-production:
    extends: sotah-server-base
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug api
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcloud-app-credentials.json
    - PROJECT_ID=$PROJECT_ID
    volumes:
    - $GOOGLE_APPLICATION_CREDENTIALS:/tmp/gcloud-app-credentials.json

  sotah-server-sync-items:
    extends: sotah-server-base
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcloud-app-credentials.json
    - PROJECT_ID=$PROJECT_ID
    volumes:
    - $GOOGLE_APPLICATION_CREDENTIALS:/tmp/gcloud-app-credentials.json
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug sync-items


  sotah-api-base:
    build: ./sotah-api
    ports:
    - "8080:8080"
    environment:
    - NATS_HOST=nats
    - NATS_PORT=4222
    - DB_HOST=db
  sotah-api:
    extends: sotah-api-base
    depends_on:
    - sotah-server-api
    - nats
    - db
    volumes:
    - ./sotah-api/app:/srv/app
    - ./sotah-server/data/item-icons:/tmp/item-icons
  sotah-api-test:
    extends: sotah-api-base
    depends_on:
    - sotah-server-api-test
    - nats
    - db
  sotah-api-production:
    extends: sotah-api-base
    depends_on:
    - sotah-server-api-production
    - nats
    - db


  sotah-client-production:
    image: ihsw/sotah-client
    ports:
    - "5000:5000"
    depends_on:
    - sotah-api-production
